### ISSUE TITLE
Localadmin module

### ISSUE THREAD

**Issue by lolipale** [munkireport/localadmin#4]
Hello,
The title of Localadmin module is "Apple Remote Desktop Report".
II suppose it's an old trace...

**Comment by bochoven** [comment]
I don't understand where do you see that?

**Comment by lolipale** [comment]
<img width="1562" alt="Capture d’écran 2019-10-02 à 16 11 23" src="https://user-images.githubusercontent.com/13834698/66051511-5263b300-e52f-11e9-839d-d9968c150ecc.png">
